BATCH_SIZE: 32
EPOCHS: 5
CLASSES: 6
NUM_WORKERS: 4
LEARNING_RATE: 3e-5
WEIGHT_DECAY: 2e-2
BETA1: 0.9
BETA2: 0.999
PIN_MEMORY: True
FOLD: 5
MAX_LEN: 200
TRAIN_SUBSET: 2000
TEST_SUBSET: 500
SEED: 34
PRE_TRAINED: bert-base-cased